version: '3'

services:
  core:
    build: ./core
    image: acme-core:latest
    depends_on:
      - redis
    ports:
      - "8092:8092"
      - "18092:18092"
    volumes:
      - ./core/sample:/usr/local/knotx/sample
  redis:
    image: redis:5
    ports:
    - "6379:6379"
