version: '3'

services:
  core:
    build: ./core
    image: acme-core:latest
    depends_on:
      - redis
    ports:
      - "3000:3000"
      - "8092:8092"
      - "18092:18092"
    volumes:
      - ./core/sample:/usr/local/knotx/sample
  redis:
    image: redis:5
    ports:
    - "6379:6379"
  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
    depends_on:
      - redis
    ports:
      - "8080:80"
